
lib{function2}: include/hxx{**} hxx{version} mxx{function2}
{
  bin.binless = true
}

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_base/include"

# Export options.
#
liba{function2}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_base/include"
}

include/
{
	hxx{*}:
	{
	  install         = include/
	  install.subdirs = true
	}
}
